.github/workflows/pull-request.yaml
README.md
devenv.nix
guppylang/hugr/hugr.py
guppylang/hugr/raw.py
poetry.lock
pyproject.toml
tests/integration/conftest.py
tests/integration/util.py
validator/Cargo.lock
validator/Cargo.toml
validator/pyproject.toml
validator/src/lib.rs

this workflow needs clarifying in readme, should be done in conjunction with guide to runnings tests, TODO.

chore: use poetry for hugr/tket2 dependencies

---

README.md
guppylang/__init__.py
ruff.toml

Closes #123 
Closes #100 
Closes #127

feat: add top-level imports

---

guppylang/compiler/expr_compiler.py
guppylang/prelude/_internal.py
validator/Cargo.lock
validator/Cargo.toml

chore: Bump to Hugr v0.2

---

guppylang/prelude/quantum.py

fix: Use correct TK2 gate names

---

guppylang/compiler/expr_compiler.py
tests/integration/test_call.py

fix: Consider type when deciding whether to pack up returns

---

guppylang/decorator.py

fix: Only use path when determining equality of implicit modules

---

guppylang/prelude/_internal.py

fix: Serialisation of float values

---

guppylang/__init__.py
guppylang/prelude/builtins.py

chore: Export py function

---

guppylang/prelude/_internal.py

fix: Serialisation of bool values

---

guppylang/compiler/cfg_compiler.py

fix: Don't reorder inputs of entry BB

---

guppylang/error.py

fix: Use correct hook for error printing inside jupyter notebooks

---

.github/workflows/pull-request.yaml

To support working on dev branches like #311

ci: Run CI for PRs targeting any branch

---

justfile

Similar to other hugrverse projects

chore: add a justfile

---

guppylang/prelude/_internal/compiler.py
guppylang/tys/builtin.py

feat: Lower linear array elements to optionals

---

guppylang/prelude/_internal/compiler/arithmetic.py
guppylang/prelude/builtins.py

feat: Support `nat`/`int` ↔ `bool` cast operations

---

guppylang/__init__.py

This gets auto-updated by release-please.

feat: Add `__version__` field to guppylang

---

guppylang/tys/ty.py

chore: Fix doctring of `NoneType`

---

guppylang/checker/linearity_checker.py
guppylang/prelude/_internal/compiler/list.py
guppylang/prelude/_internal/compiler/prelude.py
tests/integration/test_list.py

Fixes some lowering bugs for list subscripts. Also adds more tests for list subscripting (mostly copied from `test_array.py`)

fix: Fix list lowering bugs

---

.github/workflows/pull-request.yaml
execute_llvm/pyproject.toml
pyproject.toml
uv.lock

feat: remove python python 3 upper bound (support python 3.13)

---

guppylang/prelude/_internal/checker.py
tests/error/misc_errors/result_tag_too_big.err
tests/error/misc_errors/result_tag_too_big.py

feat: restrict result tag sizes to 256 bytes

---

guppylang/checker/errors/type_errors.py
guppylang/checker/expr_checker.py
guppylang/checker/stmt_checker.py
guppylang/error.py
guppylang/prelude/_internal/checker.py
guppylang/tys/param.py
tests/error/array_errors/new_array_cannot_infer.err
tests/error/array_errors/new_array_check_fail.err
tests/error/array_errors/new_array_wrong_length.err
tests/error/misc_errors/result_tag_not_static.err
tests/error/misc_errors/result_tag_not_str.err
tests/error/misc_errors/result_tag_too_big.err
tests/error/poly_errors/arg_mismatch4.err
tests/error/poly_errors/arg_mismatch5.err
tests/error/poly_errors/non_linear1.err
tests/error/poly_errors/non_linear2.err
tests/error/poly_errors/non_linear3.err
tests/error/type_errors/call_not_function.err

Closes #633
Also updates a few last errors that I overlooked in the previous refactors

feat: Get rid of old error system

---

.github/workflows/python-wheels.yml

Fix the failed wheels deployment
https://github.com/CQCL/guppylang/actions/runs/11801943251/job/32876453714

ci: Fix wheels publish config

---

guppylang/checker/func_checker.py
tests/error/misc_errors/default_arg.err
tests/error/misc_errors/default_arg.py

fix: Detect unsupported default arguments

---

.pre-commit-config.yaml
devenv.lock
devenv.nix

see drive-by typos chore in first commit 
https://github.com/crate-ci/typos/blob/master/docs/pre-commit.md

chore: use new uv devenv setup

---

docs/build.sh

fix: docs build command

---

guppylang/checker/errors/type_errors.py
tests/error/misc_errors/unsupported_const.err
tests/error/misc_errors/unsupported_const.py

fix: Properly report error for unsupported constants

---

Cargo.lock
Cargo.toml
execute_llvm/Cargo.toml
execute_llvm/src/lib.rs
guppylang/compiler/stmt_compiler.py
guppylang/std/_internal/compiler/array.py
guppylang/std/_internal/compiler/list.py
pyproject.toml
uv.lock

use the Some utility in a few places

chore: update dependency to hugr 0.10.1

---

guppylang/std/quantum.py
guppylang/std/quantum_functional.py
tests/integration/test_quantum.py

feat:  Add CH gate to the stdlib

---

devenv.nix

add missing lib to path for ubuntu

chore: update devenv.nix, add cc.lib to path

---

guppylang/checker/errors/type_errors.py
guppylang/checker/expr_checker.py
guppylang/tys/parsing.py
tests/error/poly_errors/arg_mismatch6.err
tests/error/poly_errors/arg_mismatch6.py
tests/error/poly_errors/arg_mismatch7.err
tests/error/poly_errors/arg_mismatch7.py
tests/error/poly_errors/arg_mismatch8.err
tests/error/poly_errors/arg_mismatch8.py
tests/error/poly_errors/arg_mismatch9.err
tests/error/poly_errors/arg_mismatch9.py
tests/error/poly_errors/type_apply_not_enough.err
tests/error/poly_errors/type_apply_not_enough.py
tests/error/poly_errors/type_apply_not_generic1.err
tests/error/poly_errors/type_apply_not_generic1.py
tests/error/poly_errors/type_apply_not_generic2.err
tests/error/poly_errors/type_apply_not_generic2.py
tests/error/poly_errors/type_apply_too_many.err
tests/error/poly_errors/type_apply_too_many.py
tests/integration/test_poly.py
tests/integration/test_poly_def.py

feat: Allow explicit application of type arguments

---

guppylang/diagnostic.py
tests/diagnostics/snapshots/test_message_new_line.txt
tests/diagnostics/test_diagnostics_rendering.py
tests/error/py_errors/python_err.err

fix: Fix rendering of line breaks in diagnostics

---

guppylang/std/_internal/compiler/option.py
guppylang/std/option.py
tests/integration/test_option.py
uv.lock

feat: add `Option.unwrap_nothing()` method

---

guppylang/checker/core.py
guppylang/checker/expr_checker.py
guppylang/checker/linearity_checker.py
guppylang/checker/stmt_checker.py
guppylang/compiler/expr_compiler.py
guppylang/compiler/stmt_compiler.py
tests/error/array_errors/assign_after_move.err
tests/error/array_errors/assign_after_move.py
tests/error/array_errors/assign_after_move_nested.err
tests/error/array_errors/assign_after_move_nested.py
tests/integration/test_array.py

Fixes #836 and as a drive-by also fixes #835

fix: Fix mutation of nested arrays

---

guppylang/checker/linearity_checker.py
guppylang/compiler/expr_compiler.py
guppylang/nodes.py
guppylang/std/_internal/checker.py
guppylang/std/builtins.py
tests/error/array_errors/copy_after_move.err
tests/error/array_errors/copy_after_move.py
tests/error/array_errors/non_array_copy.err

fix: Fix linearity checking for array copies

---

guppylang/definition/function.py
guppylang/definition/struct.py
tests/error/misc_errors/span_indented.err
tests/error/misc_errors/span_indented.py
tests/error/misc_errors/span_indented_struct.err
tests/error/misc_errors/span_indented_struct.py

fix: Fix diagnostic spans for indented code

---

guppylang/compiler/expr_compiler.py
tests/integration/test_array_comprehension.py

fix: Fix array comprehensions with generic element type

---

Cargo.lock
Cargo.toml
execute_llvm/src/lib.rs
guppylang/compiler/core.py
guppylang/compiler/expr_compiler.py
guppylang/nodes.py
guppylang/std/_internal/checker.py
guppylang/std/_internal/compiler/prelude.py
guppylang/std/builtins.py
pyproject.toml
tests/integration/test_panic.py
tests/integration/test_side_effect_ordering.py
uv.lock

wait to merge on hugr-py release

feat: add exit function that stops a shot

---

guppylang/std/builtins.py
tests/integration/test_arithmetic.py

fix: add missing compilation for int __rshift__

---

guppylang/definition/function.py
tests/integration/notebooks/misc_notebook_tests.ipynb
tests/integration/test_examples.py

fix: Fix diagnostics spans for dynamically defined notebook functions

---

guppylang/std/qsystem/__init__.py

fix: deprecate zz_max and define in terms of zz_phase

---

guppylang/std/builtins.py
tests/integration/test_bytecast.py

feat: Add bytecast ops to builtins

---

guppylang/std/qsystem/random.py
tests/integration/test_qsystem.py

https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle?utm_source=chatgpt.com#The_modern_algorithm

feat(std): add array shuffling to rng module

---

guppylang/diagnostic.py
tests/diagnostics/snapshots/test_far_indented_label.txt
tests/diagnostics/snapshots/test_long_label.txt
tests/diagnostics/test_diagnostics_rendering.py
tests/error/array_errors/new_array_wrong_length.err
tests/error/array_errors/non_static_comprehension.err
tests/error/comprehension_errors/capture1.err
tests/error/comprehension_errors/capture2.err
tests/error/comprehension_errors/capture3.err
tests/error/comprehension_errors/capture4.err
tests/error/comprehension_errors/multi_use1.err
tests/error/comprehension_errors/multi_use2.err
tests/error/comprehension_errors/multi_use3.err
tests/error/inout_errors/moved.err
tests/error/inout_errors/moved_if.err
tests/error/inout_errors/struct_constructor.err
tests/error/nested_errors/linear_capture.err
tests/error/poly_errors/non_linear2.err
tests/error/poly_errors/non_linear3.err
tests/error/poly_errors/pass_poly_free.err
tests/error/type_errors/unpack_tuple_starred.err

fix: Fix too narrow rendering of indented diagnostic labels

---

Cargo.lock
Cargo.toml
tests/integration/test_arithmetic.py

chore: Bump hugr version

---

guppylang/definition/traced.py
tests/error/tracing_errors/generic_function.err
tests/error/tracing_errors/generic_function.py

fix: Better error message for unsupported generic comptime functions

---

guppylang/cfg/builder.py
guppylang/checker/linearity_checker.py
guppylang/compiler/cfg_compiler.py
guppylang/compiler/expr_compiler.py
guppylang/nodes.py

Temporary hack. We should revert this once https://github.com/CQCL/hugr/issues/1234 is resolved
See #963

feat: Stop emitting non-local edges

---

guppylang/definition/custom.py
guppylang/definition/struct.py
guppylang/std/collections.py
guppylang/std/option.py
tests/integration/std/test_collections.py
tests/integration/test_poly_def.py

This mainly serves as a template for the unitary hack task to add more data structures to the standard library

feat: Add stack data structure to standard library

---

guppylang/std/qsystem/random.py
guppylang/std/qsystem/utils.py

Possible after closing of https://github.com/CQCL/guppylang/issues/826

docs: remove wrappers on random docs, add doc to get_current_shot

---

guppylang/std/collections.py
tests/integration/std/test_collections.py

Closes #974
Adds a PriorityQueue that implements a min heap under the hood.

feat: Add PriorityQueue to standard library

---

guppylang/compiler/core.py
guppylang/compiler/func_compiler.py

fix: deterministic worklist iteration order

---

docs/api-docs/conf.py
guppylang/decorator.py
guppylang/dummy_decorator.py
guppylang/std/mem.py

docs: Fix sphinx autodoc for Guppy functions

---

Cargo.lock
guppylang/compiler/expr_compiler.py
pyproject.toml
uv.lock

This reverts commit https://github.com/CQCL/guppylang/commit/0d4625d7b8fbbf287fb7a4a907bc32ec2c2d8d9f.
but keep refactors

revert: borrowing array result (#1020)

---

guppylang/engine.py

feat: store used extensions and versions in HUGR metadata

---

execute_llvm/Cargo.toml
execute_llvm/src/lib.rs
guppylang/engine.py
tests/integration/conftest.py

use to avoid passing function names to execute_llvm

feat: set hugr entrypoint to compiled function

---

guppylang/engine.py
tests/error/tracing_errors/other_diagnostics.err
tests/error/tracing_errors/other_diagnostics.py

fix: Fix diagnostics rendering for comptime entrypoints

---

guppylang/defs.py
tests/test_version_metadata.py

fix: overwrite generator metadata with guppylang version

---

guppylang-internals/src/guppylang_internals/checker/expr_checker.py
guppylang-internals/src/guppylang_internals/compiler/expr_compiler.py
tests/integration/test_none.py

fix: Support `None` value

---

.github/workflows/release-checks.yml

When testing this on the PR I fixed the test trigger, but not the final one -.-
https://github.com/CQCL/guppylang/pull/1150/commits/7424fba594d6c4d77f9df96bea8820af5bf4751b

ci: Fix release-checks trigger filter

---

.github/workflows/release-checks.yml

The fix from #1152 wasn't quite right

ci: Fix release-checks filter, again

---

guppylang-internals/src/guppylang_internals/ast_util.py

BREAKING CHANGE: RangeChecker has been deleted.

refactor!: style change to cause version bump

---

guppylang/emulator/result.py
guppylang/emulator/state.py
tests/emulator/__init__.py
tests/emulator/test_builder.py
tests/emulator/test_instance.py
tests/emulator/test_result.py
tests/emulator/test_state.py
tests/integration/test_emulator.py

Also adds unit tests for the emulator module. Disclaimer: tests were written with heavy copilot assistance.  
Closes #1183

fix: cache state extraction to allow multiple access

---

examples/state_results.ipynb
guppylang/src/guppylang/defs.py
guppylang/src/guppylang/emulator/__init__.py
guppylang/src/guppylang/emulator/instance.py
guppylang/src/guppylang/emulator/result.py
guppylang/src/guppylang/emulator/state.py
tests/emulator/test_state.py
tests/integration/std/test_collections.py

TODO:
BEGIN_COMMIT_OVERRIDE
docs: extended emulator docs
fix(emulator): incorrect pure state check
END_COMMIT_OVERRIDE

docs: extended emulator docs

---

guppylang/src/guppylang/std/lang.py
tests/integration/test_pytket_circuits.py
tests/integration/test_wasm.py
tests/integration/tracing/test_basic.py

Closes #1239
drive-by: Ruff fixes

fix: comptime should act as identity in python context 

---

guppylang-internals/src/guppylang_internals/tracing/function.py
tests/integration/tracing/test_basic.py

fix: Fix incorrect leak error for borrowing functions in comptime

---

guppylang/pyproject.toml

chore: update internals dependency to 0.24
