CQCL/guppylang

- .github/workflows/pull-request.yaml
- README.md
- poetry.lock
- pyproject.toml
pypi doesn't allow git dependencies in extras
> fix: make tket2 group rather than extra

- .github/workflows/pr-title.yml
Check that PR titles conform to conventional commits style
This is copied from `hugr`, which is a vanilla usage of `action-semantic-pull-request`
> chore: Check PR titles are conventional commits

- .github/workflows/release-please.yml
Add release action. This should check commits to main for the string "release-as: X.X.X" and open a PR for the release, creating a changelog from our conventional commits.
When this is merged, it will add a git tag and github release pointing to the merged release PR.
I've made it also check the branch `release-testing` so that we can check if it works! After testing, I'll open a PR to get rid of this line
> chore: Add release-please workflow

- pyproject.toml
- quickstart.md
> docs: Add short description and simplify readme for pypi

- guppylang/error.py
- tests/error/util.py
Instead, let the exception go through and use `sys.excepthook` to customise how the error message is printed.
Fixes #109
> fix: Stop exiting interpreter on error

- .github/workflows/pull-request.yaml
- README.md
- poetry.lock
- pyproject.toml
Also adds the badge to the README
> ci: Submit test coverage to codecov

- .github/workflows/python-wheels.yml
Builds the wheels on every push to main, and publishes the to pypi when pushing a new version tag
> ci: build wheels and publish to pypi

- guppylang/checker/expr_checker.py
- guppylang/definition/ty.py
- guppylang/prelude/_internal.py
- guppylang/tys/builtin.py
- guppylang/tys/parsing.py
This is required as a precursor for checking struct definitions
> chore: Pass globals to check_instantiate

- guppylang/ast_util.py
- guppylang/definition/struct.py
- guppylang/tys/parsing.py
Parses struct definitions of the following form:
```
class MyStruct:
field1: SomeType
field2: OtherType
...
```
As a drive-by this PR also fixes the source location annotation for types in string form
> feat: Parse struct definitions

- guppylang/compiler/expr_compiler.py
For some reason, mypy started complaining that it can no longer find `Tk2Circuit.to_hugr_json`.
I believe this was introduced in #201 but not flagged because of CI caching?
> fix: Mypy tket2 error

- .pre-commit-config.yaml
- guppylang/checker/func_checker.py
- poetry.lock
- pyproject.toml
Ruff 0.4.5 adds a new rule [UP037](https://docs.astral.sh/ruff/rules/quoted-annotation/) that triggered a CI fail.
> chore: Bump ruff to 0.4.5 and fix lint

- tests/integration/test_py.py
- tests/integration/util.py
It was introduced recently in #229
> test: update tests to use the built-in `py` export

- guppylang/decorator.py
- guppylang/definition/extern.py
- tests/error/misc_errors/extern_bad_type.err
- tests/error/misc_errors/extern_bad_type.py
- tests/error/test_misc_errors.py
- tests/integration/test_extern.py
Closes #169
It's a bit annoying that the type has to be provided as a string, but we can't represent Guppy types as Python objects on user-level yet.
> feat: Add extern symbols

- guppylang/cfg/builder.py
- guppylang/checker/expr_checker.py
- guppylang/checker/func_checker.py
- guppylang/checker/stmt_checker.py
- guppylang/compiler/expr_compiler.py
- guppylang/error.py
- guppylang/hugr_builder/hugr.py
- guppylang/module.py
- ruff.toml
- tests/integration/test_extern.py
Solves https://github.com/CQCL/guppylang/issues/65
When adding `strict=True` to all mentions of `zip`, some tests started to fail:
```bash
===================================================================================================== short test summary info =====================================================================================================
FAILED tests/error/test_linear_errors.py::test_linear_errors[/guppylang/tests/error/linear_errors/reassign_unused_tuple.py] - ValueError: zip() argument 2 is shorter than argument 1
FAILED tests/error/test_linear_errors.py::test_linear_errors[/guppylang/tests/error/linear_errors/reassign_unused.py] - ValueError: zip() argument 2 is shorter than argument 1
FAILED tests/error/test_misc_errors.py::test_misc_errors[/guppylang/tests/e …
```
> fix:  Pass strict parameter to zip function call, as recommended per the B905 linting rule

- guppylang/module.py
- tests/integration/test_basic.py
Closes #246 
I'm not sure where to add a test for this, as it's not integration nor error testing.
> feat: Return already-compiled hugrs from `GuppyModule.compile`

- tests/error/test_array_errors.py
This file should have been added with #258
> fix: Add missing test file

- release-please-config.json
To avoid spamming the release team with review requests.
> ci: Create release-please PRs as drafts

- guppylang/definition/custom.py
- tests/integration/test_poly.py
> fix: Loading custom polymorphic function defs as values

- guppylang/definition/custom.py
- guppylang/definition/struct.py
- guppylang/module.py
- tests/error/struct_errors/constructor_arg_mismatch.err
- tests/error/struct_errors/constructor_arg_mismatch.py
- tests/error/struct_errors/constructor_arg_mismatch_poly.err
- tests/error/struct_errors/constructor_arg_mismatch_poly.py
- tests/error/struct_errors/constructor_missing_arg.err
- tests/error/struct_errors/constructor_missing_arg.py
- tests/error/struct_errors/constructor_too_many_args.err
- tests/error/struct_errors/constructor_too_many_args.py
- tests/integration/test_poly.py
- tests/integration/test_struct.py
> feat: Generate constructor methods for structs

- guppylang/prelude/_internal.py
- guppylang/prelude/builtins.py
- tests/error/misc_errors/result_tag_not_int.err
- tests/error/misc_errors/result_tag_not_int.py
- tests/error/misc_errors/result_tag_not_static.err
- tests/error/misc_errors/result_tag_not_static.py
- tests/error/misc_errors/result_value_linear.err
- tests/error/misc_errors/result_value_linear.py
- tests/integration/test_result.py
> feat: Add result function

- guppylang/cfg/builder.py
- guppylang/checker/cfg_checker.py
- guppylang/checker/core.py
- guppylang/checker/expr_checker.py
- guppylang/checker/func_checker.py
- guppylang/checker/linearity_checker.py
- guppylang/checker/stmt_checker.py
- guppylang/compiler/cfg_compiler.py
- guppylang/compiler/core.py
- guppylang/compiler/expr_compiler.py
- tests/error/comprehension_errors/guarded2.err
- tests/error/comprehension_errors/guarded2.py
- tests/error/comprehension_errors/pattern_override2.err
- tests/error/comprehension_errors/pattern_override2.py
- tests/error/linear_errors/break_unused.py
- tests/error/linear_errors/continue_unused.py
> refactor: Turn linearity checking into separate compiler stage

- guppylang/hugr_builder/hugr.py
- poetry.lock
- pyproject.toml
Backwards compatible other than an import interface
Does not actually use the new builder yet, to come.
> chore: update to hugr-py 0.3

- guppylang/cfg/analysis.py
- guppylang/cfg/bb.py
- guppylang/cfg/cfg.py
- guppylang/checker/core.py
- guppylang/checker/expr_checker.py
- guppylang/checker/linearity_checker.py
- guppylang/hugr_builder/visualise.py
Makes the dataflow analysis and local variable map generic over the type used to index into them.
This is a precursor for making the analysis track struct fields separately. See #295 for context.
> chore: Make locals and analysis generic over key type

- guppylang/cfg/builder.py
- guppylang/checker/func_checker.py
- guppylang/compiler/func_compiler.py
- guppylang/decorator.py
- guppylang/definition/declaration.py
- guppylang/definition/function.py
- guppylang/nodes.py
- tests/integration/test_docstring.py
Parse docstrings for functions, including nested functions. We don't do anything with them for now, but previously we didn't recognise them and threw an "Unsupported constant" error (trying to interpret the statement as a string expression)
Docstrings for structs are TODO, and probably a separate PR
> feat: Parse docstrings for functions

- guppylang/compiler/expr_compiler.py
- guppylang/nodes.py
- guppylang/prelude/_internal.py
- guppylang/prelude/builtins.py
Fixes #320.
We were relying on a hack where the `CustomCallChecker` for the `result(tag, value)` function inserted an extra type arg for the tag that wasn't declared in the signature of `result`. This now leads to problems in #321
For now, the only way to fix this is to add a new node to the AST that handles compilation of results with tags.
In the future, we could solve this more elegantly by for example adding `Literal` types which would allow us to specify the tag type arg in argument position:
```python
def result[n, T](tag: Literal[n], value: T) -> None: ...
```
> chore: Turn result function into an AST node

- guppylang/checker/cfg_checker.py
- guppylang/checker/func_checker.py
- guppylang/checker/linearity_checker.py
- guppylang/compiler/cfg_compiler.py
- guppylang/definition/function.py
- guppylang/nodes.py
- tests/error/comprehension_errors/pattern_override2.err
- tests/error/linear_errors/if_both_unused_reassign_field.err
- tests/integration/test_linear.py
Fixes  #337.
The fix for the linearity checker is easy: When checking assignments, only complain if a *local* unused linear variable is shadowed.
However, correctly lowering the program in #337 to Hugr requires some additional changes to Hugr codegen. Namely, we need to consider if a BB uses a *whole* struct `s` or only some of its fields. In the latter case, we should only feed those used values into the BB. This requires specifying the signature of BBs in the form of `Place`s rather than `Variable`s.
Concretely, this PR does the following:
* Make `Signature` generic over the representation of program variables so it can capture both `Variable` and `Place`
* Similarly, make `CheckedBB` and `CheckedCFG` generic
* During checking, we first construct a `CheckedCFG[Variable]` which then gets …
> fix: Use places in BB signatures for Hugr generation

- guppylang/checker/func_checker.py
- guppylang/definition/struct.py
- guppylang/definition/ty.py
- guppylang/tys/builtin.py
- guppylang/tys/parsing.py
- tests/error/inout_errors/nonlinear.err
- tests/error/inout_errors/nonlinear_callable.err
- tests/error/inout_errors/nonlinear_callable.py
- tests/error/misc_errors/nested_arg_flag.err
- tests/error/misc_errors/nested_arg_flag.py
- tests/error/misc_errors/return_flag.err
- tests/error/misc_errors/return_flag.py
- tests/error/misc_errors/return_flag_callable.err
- tests/error/misc_errors/return_flag_callable.py
- tests/integration/test_inout.py
> feat: Move flag parsing into arg_from_ast

- guppylang/checker/linearity_checker.py
- tests/error/linear_errors/while_unused.err
- tests/error/linear_errors/while_unused.py
Fixes #354.
When checking for unused linear variables, we should look at *all* variables in scope, not only the ones that were defined in the current BB
> fix: Linearity checking bug

- .github/workflows/pull-request.yaml
- poetry.lock
- pyproject.toml
- tests/integration/conftest.py
- tests/integration/test_py.py
- tests/integration/test_tket.py
- tests/util.py
Adds the tests removed from tket2 in https://github.com/CQCL/tket2/pull/516
This requires a tket2 alpha release to avoid the git ref dependency.
> test: guppy -> pytket lowering with tket2

- guppylang/compiler/expr_compiler.py
Closes https://github.com/CQCL/tket2/issues/529
> fix: Fix invalid result operation name

- guppylang/definition/struct.py
Fixes #373.
Trying to do `inspect.getsourclines` for a class defined in a notebook yields an `OSError: source code not available`. See
* https://github.com/ipython/ipython/issues/11249
* https://bugs.python.org/issue33826
The fix suggested in https://github.com/ipython/ipython/issues/11249 only works for classes with methods. Instead, I'm using a solution inspired by https://github.com/wandb/weave/pull/1864 that retrieves the cell sources of the active IPython session and searches them one by one.
> fix: Fix struct definitions in notebooks

- examples/random_walk_qpe.py
- guppylang/checker/expr_checker.py
- poetry.lock
- ruff.toml
- tests/integration/test_result.py
Fixes the lints in `ruff 0.6` that caused CI errors in https://github.com/CQCL/guppylang/pull/386
> chore: Update ruff and fix lints

- .github/workflows/pull-request.yaml
- .pre-commit-config.yaml
- tests/integration/conftest.py
- tests/integration/test_functional.py
Ensures that the checks run by pre-commit are the same as the ones run in CI, and the `ruff` and `mypy` versions are always controlled by `pyproject.toml`.
Before, we used pre-commit actions with their own versions that needed to be updated separately and tended to get out of date.
drive-by: Fix ruff lints added in the latest version
> chore: Use local ruff and mypy for pre-commit checks

- guppylang/prelude/builtins.py
- tests/integration/test_if.py
> feat: Add equality test for booleans

- execute_llvm/Cargo.lock
- execute_llvm/Cargo.toml
- tests/integration/test_arithmetic.py
Update hugr_llvm so that we get lowering for multiply and divide. Test the new functionality
Drive-by: Fix inkwell to version 0.4.0 - the new release (0.5.0) has just come out and has api breaking changes
> chore: Update hugr llvm and test new op lowering

- guppylang/checker/expr_checker.py
- guppylang/checker/linearity_checker.py
- guppylang/compiler/expr_compiler.py
- guppylang/nodes.py
- tests/error/linear_errors/method_capture.err
- tests/error/linear_errors/method_capture.py
- tests/integration/test_call.py
- tests/integration/test_higher_order.py
- tests/integration/test_struct.py
Closes  #439.
* Add a new `PartialApply` node to create a closure capturing the `self` argument of methods
* Calls of partial applies are simplified to direct calls
* Higher-order usage of methods is only allowed if `self` is not linear
> feat: Allow calling of methods

- guppylang/checker/linearity_checker.py
- tests/integration/test_inout.py
- tests/integration/test_linear.py
Fixes #438.
When checking that all live linear places in scope are definitely used, we have to be more careful about determining whether variables are *actually* live rather than only being included in scope because of the less precise first pass of liveness analysis.
> fix: Fix linearity checking bug

- guppylang/compiler/cfg_compiler.py
- guppylang/decorator.py
- guppylang/module.py
- tests/error/misc_errors/return_flag_callable.err
- tests/error/misc_errors/return_flag_callable.py
- tests/integration/modules/mod_a.py
- tests/integration/modules/mod_b.py
- tests/integration/modules/mod_c.py
- tests/integration/test_imports.py
Closes #425 and closes #427 and closes #134
* Allow importing of function definitions (before we could only import declarations)
* Until we have Hugr linking, we just lower everything into the same Hugr. This requires some changes to the compilation logic:
- Differentiate between checking (`module.check()`) and full Hugr compilation (`module.compile()`) of modules
- Importing modules only checks them
- Hugr lowering is done at the end in one step over all imported modules
* Allow to import individual definitions instead of whole modules
* Allow aliased imports using kwargs (see test examples)
> feat: Allow imports of function definitions and aliased imports

- guppylang/checker/linearity_checker.py
- guppylang/compiler/expr_compiler.py
- guppylang/definition/custom.py
- guppylang/definition/struct.py
- guppylang/prelude/_internal/checker.py
- guppylang/prelude/_internal/compiler.py
- guppylang/prelude/builtins.py
- guppylang/tys/builtin.py
- tests/error/array_errors/new_array_cannot_infer.err
- tests/error/array_errors/new_array_cannot_infer.py
- tests/error/array_errors/new_array_check_fail.err
- tests/error/array_errors/new_array_check_fail.py
- tests/error/array_errors/new_array_elem_mismatch1.err
- tests/error/array_errors/new_array_elem_mismatch1.py
- tests/error/array_errors/new_array_elem_mismatch2.err
- tests/error/array_errors/new_array_elem_mismatch2.py
- tests/error/array_errors/new_array_wrong_length.err
- tests/error/array_errors/new_array_wrong_length.py
- tests/integration/test_array.py
Closes #396.
* New arrays can be created using the constructor `array(x, y, z)`.
* Uses a `CustomCallChecker` to support varargs
* This broke some code that relied on the static signature of functions. Added special cases for `CustomFunctions` without known signature (such as the array constructor) that infers a concrete signature based on the context.
> feat: Add array literals

- guppylang/checker/core.py
- guppylang/definition/struct.py
- guppylang/module.py
- tests/integration/test_redefinition.py
Closes #431.
* Make `Globals.defs` mutable
* Add `GuppyModule.unregister` function to remove definitions from a module
* Redefining of classes doesn't work because of #456
> feat: Skip checking of redefined functions

- .github/workflows/pull-request.yaml
- tests/integration/conftest.py
Many hugr-building tests are showing up as `s` == skipped after #455. We need to `cargo build` the validator first.
Also "fix" (perhaps hack) `run_int_fn` to extract the first `module` Hugr from the Package coming back from compilation.
> test: cargo build validator in CI

- guppylang/definition/common.py
- guppylang/tys/parsing.py
- uv.lock
Implement `__str__` for `DefId`, so it's easier to see the module name
before:
```py
DefId(id=298, module=<guppylang.module.GuppyModule object at 0x109e18110>)
```
after:
```py
DefId(298, quantum)
```
drive-by: Update uv.lock with the latest release version
> chore: Small error print improvements

- tests/integration/test_array.py
- tests/integration/test_if.py
- tests/integration/test_poly.py
- tests/integration/test_py.py
- uv.lock
Some leftover skips from the hugr update, and from https://github.com/CQCL/guppylang/issues/343
Also adds some extra info on the remaining skips.
> chore: Unskip now-passing tests

- guppylang/module.py
> fix: Initialise _checked in GuppyModule

- guppylang/checker/linearity_checker.py
- tests/integration/test_inout.py
I don't think this is the best/neatest solution, but it fixes the false positives
> fix: Evade false positives for inout variable usage

- guppylang/module.py
- tests/integration/test_redefinition.py
Closes #498.
The problem was that the autogenerated `__new__` method of structs wasn't added to `globals.defs`, yielding a `KeyError` when trying to unregister it before overriding.
> fix: Fix redefinition of structs

- README.md
- tests/conftest.py
- tests/integration/conftest.py
pytest previously skipped the validation tests if the validator was not built, leading to the situation in #468 where many tests were accidentally skipped in CI.
Instead, fail the tests if the validator is not installed, but allow `pytest --no_validation` to skip them instead.
The possibility of doing similar for execution tests (somewhat-silently skipped if `execute-llvm` isn't installed) is left for a later PR.
> test: only skip validation tests when given explicit flag

- guppylang/__init__.py
- guppylang/cfg/builder.py
- guppylang/checker/expr_checker.py
- guppylang/experimental.py
- guppylang/module.py
- guppylang/tys/builtin.py
- tests/conftest.py
- tests/error/experimental_errors/function_tensor.err
- tests/error/experimental_errors/function_tensor.py
- tests/error/experimental_errors/linst_type.err
- tests/error/experimental_errors/linst_type.py
- tests/error/experimental_errors/list_comprehension.err
- tests/error/experimental_errors/list_comprehension.py
- tests/error/experimental_errors/list_literal.err
- tests/error/experimental_errors/list_literal.py
- tests/error/experimental_errors/list_type.err
- tests/error/experimental_errors/list_type.py
- tests/error/test_experimental_errors.py
Closes #437.
BREAKING CHANGE: Lists and function tensors are no longer available by default. `guppylang.enable_experimental_features()` must be called before compilation to enable them.
> feat!: Hide lists and function tensors behind experimental flag

- guppylang/prelude/_internal/compiler/quantum.py
- guppylang/prelude/quantum.py
- guppylang/prelude/quantum_functional.py
- tests/integration/test_quantum.py
> feat: Add missing tket2 quantum gates, generalise RotationCompile

- guppylang/tys/param.py
- guppylang/tys/printing.py
- tests/error/array_errors/linear_len.err
- tests/test_type_printing.py
> fix: Fix printing of generic function parameters

- guppylang/diagnostic.py
- guppylang/span.py
> feat: Add span and diagnostics base classes

- guppylang/decorator.py
- guppylang/definition/common.py
- guppylang/definition/const.py
- guppylang/definition/custom.py
- guppylang/definition/declaration.py
- guppylang/definition/extern.py
- guppylang/definition/function.py
- guppylang/definition/struct.py
- guppylang/module.py
- guppylang/span.py
We used to store the entire source code that was used to build an AST as a field within *every node* of the AST. This was a hack so that we can render the source line from an AST node when an error occurs. With our new diagnostics system, we should do better than that!
With this PR, we cache the source of every file accessed by the compiler in a new `SourceMap` class. Then, we can look up the source associated with a span when rendering a diagnostic.
Note that we can't rely on Pythons `linecache` since we also need to keep track of cells in jupyter notebooks as individual "files".
> feat: Cache accessed source files

- Cargo.lock
- Cargo.toml
- devenv.lock
- devenv.nix
- execute_llvm/Cargo.toml
- execute_llvm/src/lib.rs
- guppylang/checker/expr_checker.py
- guppylang/compiler/expr_compiler.py
- guppylang/decorator.py
- guppylang/definition/common.py
- guppylang/module.py
- justfile
- pyproject.toml
- tests/error/py_errors/tket2_not_installed.err
- tests/integration/conftest.py
- tests/integration/test_quantum.py
- tests/util.py
- uv.lock
- validator/Cargo.toml
- temporarily disable pytket optional dependencies
- Update hugr-llvm for execute to branch to use re-exports
- separate validator and executor hugr deps to reduce chance of conflicts
- add executor building to justfile
BREAKING CHANGE: pytket optional depenedencies removed
> chore!: update hugr-py to 0.9

- guppylang/decorator.py
- guppylang/definition/common.py
- guppylang/definition/function.py
- guppylang/module.py
- tests/integration/conftest.py
- tests/integration/test_array.py
- tests/integration/test_basic.py
- tests/integration/test_extern.py
- tests/integration/test_quantum.py
- tests/util.py
Closes #559 
Is it valid to assume there is always a top-level funcdef or funcdecl for a Definition.compile()?
BREAKING CHANGE: decorator `compile_module` and `GuppyModule.compile` return `ModulePointer` rather than `Package` (package can be retrieved using `ModulePointer.package`. `Definition.compile` returns a `Func{Defn/Decl}Pointer`.
> feat!: return packages with pointers when compiling

- guppylang/prelude/_internal/compiler/list.py
- guppylang/prelude/builtins.py
Now that https://github.com/CQCL/hugr/issues/1543 is fixed, we can use the correct op for list length lowering
> fix: Fix lowering of list.__len__

- guppylang/prelude/_internal/compiler/array.py
- guppylang/prelude/_internal/compiler/list.py
- guppylang/prelude/_internal/compiler/prelude.py
- guppylang/tys/builtin.py
- tests/integration/test_array.py
Fixes #573 together with other list lowering issues.
There were some inconsistencies whether `None` is `Tag(0)` or `Tag(1)`. Now we consistently use `ht.Option` and the `build_unwrap` helper.
> fix: Fix array lowering bugs

- DEVELOPMENT.md
- README.md
- justfile
Mostly copied from HUGR's.
drive-by: Remove "experimental execution" (`guppy-runner`) section from the readme.
> docs: Add DEVELOPMENT.md

- guppylang/prelude/quantum.py
- tests/integration/test_inout.py
Extends the fact that allocation is tied to the `qubit` type by implementing measure/discard methods.
Note this includes a drive-by `measure_reset` operation which avoids resetting the qubit and just flip, might not be something to add in this PR.
> feat: add `qubit` discard/measure methods

- guppylang/diagnostic.py
- tests/diagnostics/snapshots/test_advanced_formatting.txt
- tests/diagnostics/test_diagnostics_rendering.py
Sub-diagnostics now store a pointer to their parent main diagnostic that is used to look up field values when formatting labels and messages.
This is achieved by subclassing `string.Formatter` to implement the custom lookup
> feat: Allow sub-diagnostic labels to refer to fields of their parent

- .github/workflows/docs.yml
- .github/workflows/pull-request.yaml
- DEVELOPMENT.md
- devenv.lock
- pyproject.toml
- uv.lock
[PEP 735](https://peps.python.org/pep-0735/) specifies the syntax for listing development dependencies in `pyproject.toml` in a package manager-agnostic way.
`uv 0.4.27` includes support for this, so we can now cleanup our pyproject.
drive-by: Use `--frozen --python` for `uv sync` in CI, to ensure we are using the right dep versions.
> chore: PEP 735 dev dependencies

- guppylang/checker/core.py
- guppylang/definition/custom.py
- guppylang/prelude/_internal/checker.py
- guppylang/prelude/builtins.py
- guppylang/tys/builtin.py
- tests/integration/test_range.py
Adds a new wrapper type `SizedIter` to the standard library that annotates an iterator with a static size hint. This will be used for example in array comprehensions to infer the size of the resulting array. The type gets erased when lowering to Hugr.
Updates the `range` function to emit such a size hint when the range stop is given by a static number. For example the expression `range(10)` is typed as `SizedIter[Range, 10]` whereas `range(n + 1)` is typed as `Range`. Currently, this is implemented via a `CustomCallChecker`, but in the future we could use function overloading and `Literal` types to implement this in Guppy source:
```python
@guppy.overloaded
def range[n: nat](stop: Literal[n]) -> SizedIter[Range, n]:
return SizedIter(Range(0, stop))
@guppy.overloaded
def range(stop: int) …
```
> feat: Add `SizedIter` wrapper type

- guppylang/checker/errors/type_errors.py
- guppylang/checker/stmt_checker.py
- tests/error/struct_errors/assign_call.err
- tests/error/struct_errors/invalid_attribute_access.err
- tests/error/struct_errors/invalid_attribute_assign1.err
- tests/error/struct_errors/invalid_attribute_assign2.err
- tests/error/struct_errors/invalid_attribute_assign3.err
- tests/error/struct_errors/mutate_classical.err
- tests/error/type_errors/unpack_not_enough.err
- tests/error/type_errors/unpack_too_many.err
> feat: Update statement checker to use new diagnostics

- guppylang/decorator.py
- guppylang/module.py
Fixes #583
The problem was that sphinx autodoc got confused by `@guppy` decorated functions. Now, we mock the decorator when we detect that sphinx is running.
> fix: Mock guppy decorator during sphinx builds

- guppylang/decorator.py
See failing run here https://github.com/CQCL/guppylang/actions/runs/11782620057/job/32818047506
The problem was that `_GuppyDummy` was missing the `_sources` field, so it didn't mock `_Guppy` correctly
> docs: Fix docs build

- release-please-config.json
Manual config required after the out-of-branch `0.12.2` release.
We'll need to remove this change in the release PR.
Release-As: 0.13.0
> chore: Manually set last release commit

- guppylang/hresult.py
- tests/test_hresult.py
- uv.lock
just a drive by I happened to do while debugging something else. Performance gains are not a bottleneck but it is more readable so might as well.
> refactor: use `OutcomeArray.from_ints` in `HShots.to_pytket`

- guppylang/std/_internal/compiler/prelude.py
- guppylang/std/builtins.py
- tests/integration/test_array.py
not sure if prelude is best place for the custom compiler
also not sure about name `mem_swap` but don't want to confuse with quantum logic swap
...And not sure about the test location either.
Closes #652
// to coerce release-please: 
Release-As: 0.13.1
> feat: mem_swap function for swapping two inout values

- pyproject.toml
> chore: Add `classifiers` to `pyproject.toml`

- .github/workflows/docs.yml
Based on hugr's [unsoundness check](https://github.com/CQCL/hugr/blob/main/.github/workflows/unsoundness.yml#L43-L56) notification.
> ci: Open an issue when building docs fails on `main`

- guppylang/std/_internal/compiler/quantum.py
- guppylang/std/qsystem/__init__.py
- guppylang/std/qsystem/functional.py
- guppylang/std/quantum.py
- guppylang/std/quantum_functional.py
- pyproject.toml
- tests/integration/test_inout.py
- tests/integration/test_linear.py
- tests/integration/test_qsystem.py
- tests/integration/test_quantum.py
- tests/integration/test_tket.py
- uv.lock
Closes #625 Closes #645
- hseries renamed to qsystem
BREAKING CHANGE: hseries primitive functions moved to std.qsystem
BREAKING CHANGE: measure_return renamed to `project_z`
> feat!: qsystem std functions with updated primitives

- .github/workflows/docs.yml
The message should go before the url.
See pre-edit message in https://github.com/CQCL/guppylang/issues/680.
> ci: Fix docs fail issue formatting

- guppylang/std/quantum.py
- tests/integration/test_qalloc.py
- tests/integration/test_quantum.py
`tket2.quantum.QAlloc` now guarantees 0 state
BREAKING CHANGE: `dirty_qubit` function removed
> feat!: remove dirty_qubit

- guppylang/decorator.py
- guppylang/definition/ty.py
- guppylang/std/_internal/compiler/option.py
- guppylang/std/option.py
- tests/integration/test_option.py
Closes #667.
Also generalises the `@guppy.type` decorator to handle generic types.
> feat: Add Option type to standard library

- guppylang/ast_util.py
Closes https://github.com/quantinuum-dev/guppy-integration/issues/33
> fix: remove use of deprecated Ellipsis

- guppylang/checker/expr_checker.py
- guppylang/definition/custom.py
- guppylang/std/_internal/checker.py
- guppylang/tys/printing.py
- guppylang/tys/ty.py
- tests/integration/test_arithmetic.py
> feat: Implicit coercion of numeric types

- guppylang/checker/expr_checker.py
- tests/integration/test_if.py
> fix: Ensure `int`s can be treated as booleans

- guppylang/std/_internal/checker.py
- tests/integration/test_range.py
> feat: Allow generic nat args in statically sized ranges

- guppylang/checker/expr_checker.py
- guppylang/compiler/expr_compiler.py
- tests/error/py_errors/list_empty.err
- tests/integration/test_py.py
Closes #545.
BREAKING CHANGE: Lists in `py(...)` expressions are now turned into Guppy arrays instead of lists.
> feat!: Turn py expression lists into arrays

- guppylang/checker/expr_checker.py
- guppylang/std/builtins.py
- guppylang/tys/builtin.py
- tests/error/py_errors/negative_nat.err
- tests/error/py_errors/negative_nat.py
- tests/integration/test_arithmetic.py
- tests/integration/test_py.py
- tests/integration/test_range.py
> fix: Accept non-negative int literals and py expressions as nats

- tests/integration/conftest.py
- tests/integration/test_arithmetic.py
Uses `pytest.approx`, see https://docs.pytest.org/en/stable/reference/reference.html#pytest-approx, with optional configurable `rel` and `abs`.
> test: rfc: refactor: run_float_fn -> run_float_fn_approx

- Cargo.lock
- Cargo.toml
- execute_llvm/Cargo.toml
- execute_llvm/src/lib.rs
- guppylang/std/_internal/compiler/array.py
- guppylang/std/_internal/compiler/list.py
- guppylang/std/_internal/util.py
- guppylang/tys/builtin.py
- pyproject.toml
- uv.lock
- validator/Cargo.toml
Closes #720 
~Waiting for tket2 release~
> feat: update to hugr 0.10 and tket2 0.6

- guppylang/compiler/stmt_compiler.py
- guppylang/std/_internal/compiler/array.py
- tests/integration/test_unpack.py
Adds the Hugr lowering for #649. See #688 for the base PR that adds the checking logic
> feat: Lower unpacking assignment of iterables to Hugr

- Cargo.lock
- Cargo.toml
- execute_llvm/Cargo.toml
- execute_llvm/src/lib.rs
- guppylang/compiler/expr_compiler.py
- guppylang/compiler/stmt_compiler.py
- guppylang/std/_internal/compiler/array.py
- guppylang/std/builtins.py
- guppylang/tys/builtin.py
- pyproject.toml
- tests/integration/test_array.py
- tests/integration/test_array_comprehension.py
- tests/integration/test_unpack.py
- uv.lock
Bumps to Hugr on main and fixes some bugs to make arrays executable.
> fix: Fix array execution bugs

- guppylang/checker/stmt_checker.py
- tests/error/array_errors/mutate.err
- tests/error/array_errors/mutate.py
> fix: Properly report errors for unsupported subscript assignments

- guppylang/hresult.py
- tests/test_hresult.py
To enable e.g. all the elements of an array to be collated in to the same bitstrings, see tests
Flattens lists so can be used once entire arrays can be printed too.
So some guppy that looks like for a given shot:
```python
vals = (1, 0, 1, 0)
for v in vals:
result("c", v)
```
results in post-processed output, over 100 shots
```python
Counter({(("c", 1010"),): 100})
```
> feat: result appending post-processing

- guppylang/std/builtins.py
- tests/integration/test_arithmetic.py
implement with not and equality for now - can be replaced with op once https://github.com/CQCL/hugr/issues/1418 is done
Closes #750
> feat: add boolean xor support

- guppylang/checker/core.py
- guppylang/definition/declaration.py
- guppylang/definition/function.py
- guppylang/definition/pytket_circuits.py
- guppylang/definition/struct.py
- tests/test_pytest_hang.py
Fixes #569.
Ensure termination of `repr` calls on objects in the compiler by excluding `python_scope` fields due to cyclic references.
See https://github.com/CQCL/guppylang/issues/569#issuecomment-2573157994 for a more detailed description of how this fixes the pytest issue.
> fix: Fix pytest hanging

- guppylang/compiler/expr_compiler.py
- guppylang/nodes.py
- guppylang/std/_internal/checker.py
- guppylang/std/_internal/compiler/prelude.py
- guppylang/std/builtins.py
- tests/error/misc_errors/panic_msg_empty.err
- tests/error/misc_errors/panic_msg_empty.py
- tests/error/misc_errors/panic_msg_not_str.err
- tests/error/misc_errors/panic_msg_not_str.py
- tests/error/misc_errors/panic_tag_not_static.err
- tests/error/misc_errors/panic_tag_not_static.py
- tests/integration/test_panic.py
- tests/integration/test_quantum.py
> feat: add `panic` builtin function

- guppylang/definition/struct.py
We forgot to add the notebook cell to the source map, resulting in internal errors when emitting a diagnostic for structs in Jupyter notebooks
> fix: Fix error printing for structs defined in notebooks

- CHANGELOG.md
- DEVELOPMENT.md
- README.md
- guppylang/std/_internal/compiler/quantum.py
- guppylang/std/qsystem/__init__.py
- guppylang/std/qsystem/utils.py
- pyproject.toml
- tests/integration/test_qsystem.py
Closes: #798
It's not clear to me whether the type in tket2-hseries for `get_current_shot()` should be `usize` or `int(6)`. I used usize initially but got the following runtime error during json validation (`[] -> [tket2.qsystem.utils][usize] but stored signature was [] -> [tket2.qsystem.utils][int(6)]`):
```py
tests/integration/conftest.py:64: in validate_impl
validate_json(js)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
hugr = '{"modules":[{"version":"live","nodes":[{"parent":0,"op":"Module"},{"parent":0,"op":"FuncDefn","name":"test","signatur..."i":1,"b":"A"}],"output":[{"t":"R","i":2,"b":"A"}],"runtime_reqs":["guppylang"]}},"binary":false,"lower_funcs":[]}}}]}'
def validate_json(hugr: str):
p = subprocess.run(  # noqa: S603
[validator, "validate", "-"],
text=True,
input=hugr, …
```
> feat: add `get_current_shot()` to qsystem module

- guppylang/std/angles.py
- tests/integration/test_arithmetic.py
Closes #761
BREAKING CHANGE: `angle.{__mul__, __rmul__, __truediv__, __rtruediv__` now take a `float` instead of an `int`.
> feat!: Generalise scalar angle operations to float

- guppylang/cfg/bb.py
- tests/integration/test_array.py
> fix: Correctly handle assignments of arrays in control-flow

- guppylang/error.py
- guppylang/module.py
- tests/error/misc_errors/check_error.err
- tests/error/misc_errors/check_error.py
- tests/error/misc_errors/implicit_load_error.err
- tests/error/misc_errors/implicit_load_error.py
- tests/error/misc_errors/load_error.err
- tests/error/misc_errors/load_error.py
- tests/error/util.py
Fixes #851
This also fixes the same issue when `load` or `load_all` is called since they rely on `check`.
Drive-by: Get rid of the horrible hack to capture diagnostics in error tests. This broke, now that check is also decorated with `pretty_errors` and I found a better way to do the same thing
> fix: Fix compiler diagnostics when calling `check` instead of `compile`

- guppylang/compiler/core.py
- tests/integration/test_side_effect_ordering.py
Closes #853
This is a temporary solution until we properly solve #778. Therefore, the implementation is somewhat hacky as we're going to remove this in the future anyways. 
The approach is to monkey-patch the `Hugr.add_node` method to implicitly insert state-order edges between nodes that could have side-effects. The list of side-effectful nodes is hard-coded in the compiler.
Also relies on the fix from https://github.com/CQCL/hugr/pull/1971, so we should wait to merge until `hugr-py` is released
> fix: Prevent reordering of operations with side-effects

- guppylang/decorator.py
Fixes #842 
The docs build broke since `guppyland.std.option` now calls `guppy.get_module` but this function was missing from the `guppy` decorator mock
> docs: Fix API docs build

- release-please-config.json
`uv 0.6.6` adds a hard error when the version of the package in `uv.lock` does not match the one declared in the editable wheel: https://github.com/astral-sh/uv/pull/12235.
`release-please` doesn't update the lock files automatically, so release PRs needed a manual lock update.
This PR adds the lockfile as an `extra-file`, to avoid this manual step.
Note that the _jsonpath_ in the config is not technically correct, as release-please's json array filters don't quite work for toml files. See https://github.com/googleapis/release-please/issues/2455, which includes this hacky workaround.
> ci: Update uv.lock on release-please PRs

- guppylang/std/qsystem/random.py
- tests/integration/test_qsystem.py
For random_nat, see: quantinuum-dev/hugrverse#138
Discussion on maybe_rng at https://github.com/CQCL/guppylang/pull/822#issuecomment-2741571177
BREAKING CHANGE: removed `random.RNG.random_nat()` and `random.maybe_rng()`
> fix(qsystem)!: remove `random_nat` and `maybe_rng`

- guppylang/std/builtins.py
Unfortunately the wrapper function trick doesn't work for variadic `*args` functions. Ready for https://github.com/CQCL/guppylang/issues/826
> docs: add supported range to `exit` docstring

- guppylang/qsys_result.py
- guppylang/std/builtins.py
`typing_extensions` defines a `@deprecated` decorator compatible with `python<3.13`
> chore: Enable deprecation warnings on pre-313 python

- guppylang/__init__.py
- guppylang/std/builtins.py
This is to improve API docs for the Guppy standard library.
Also added some docstrings as a drive-by.
> chore: Remove duplicate classes in builtins

- guppylang/decorator.py
- guppylang/std/angles.py
A first start at improving mypy complaints on Guppy code.
This PR changes the type annotations on the `guppy` decorator to pretend that they return functions/classes with the same signature.
Closes #890
> chore: Improve decorator type annotations

- guppylang/checker/linearity_checker.py
- guppylang/compiler/expr_compiler.py
- guppylang/nodes.py
- guppylang/std/_internal/checker.py
- tests/error/inout_errors/result_array_after_move.err
- tests/error/inout_errors/result_array_after_move.py
- tests/integration/test_result.py
> feat: Array results

- guppylang/checker/errors/type_errors.py
- guppylang/checker/expr_checker.py
- guppylang/tys/param.py
- tests/error/poly_errors/non_linear2.err
- tests/error/poly_errors/non_linear3.err
- tests/error/poly_errors/non_linear4.err
- tests/error/poly_errors/non_linear4.py
- tests/error/poly_errors/type_arg_not_copyable.err
- tests/error/poly_errors/type_arg_not_copyable.py
- tests/error/poly_errors/type_arg_not_droppable.err
- tests/error/poly_errors/type_arg_not_droppable.py
> fix: Use correct copyable/droppable terminology for type arg errors

- guppylang/std/_internal/checker.py
- tests/integration/test_array.py
Fixes #939
The problem was that we forgot to store the inferred type args in the constructor call and instead just reused the previous `ty.args` which could still contain free type variables
> fix: Fix resolution of generic lengths in array constructor

- guppylang/decorator.py
- tests/integration/tracing/test_basic.py
> fix: Capture entire Python scope when defining comptime functions

- guppylang/tracing/object.py
- tests/integration/tracing/test_arithmetic.py
Fixes #946
The problem was that `pi` is a `@guppy.constant` (i.e. a `GuppyDefinition` at comptime) which didn't implement the corresponding `__add__` etc dunder methods.
I fixed this by making `GuppyDefinition` inherit from `DunderMixin` as well as refactoring the `binary_operation` and `unray_operation` wrappers to first load definitions as values (via `guppy_object_from_py`) before calling the methods.
> fix: Fix comptime angle arithmetic

- Cargo.lock
- Cargo.toml
- execute_llvm/src/lib.rs
- guppylang/definition/pytket_circuits.py
- guppylang/std/_internal/compiler/array.py
- pyproject.toml
- uv.lock
BREAKING CHANGE: Generated HUGRs now refer to entrypoints and are always modules in envelopes.
> feat!: hugr 0.20 bump

- guppylang/definition/custom.py
- guppylang/definition/struct.py
- tests/integration/test_poly_def.py
Fixes #970
The fix also closes #393
> fix: Stop monomorphising higher-order custom function values

- justfile
Otherwise, it uses `sh` which doesn't recognize the `[[` ... `]]` syntax:
```
[[ -n "${JUST_INHIBIT_GIT_HOOKS:-}" ]] || uv run pre-commit install -t pre-commit
sh: 1: [[: not found
```
> fix: Specify bash shell in justfile.

- guppylang/definition/extern.py
- guppylang/std/_internal/compiler/prelude.py
- pyproject.toml
- uv.lock
~wait to merge: for HUGR patch release containing deprecation of `Extension.extensions` field~ Done with hugr 0.12.1
https://github.com/CQCL/hugr/pull/2233
> fix: stop using value ExtensionSet

- guppylang/hresult.py
- guppylang/qsys_result.py
- guppylang/std/qsystem/__init__.py
drive-by keep zz_max as a library function
BREAKING CHANGE: deprecated `hresult` and `qsys_result` modules have been removed. Use `hugr.qysystem.result` directly.
> refactor!: delete deprecated result modules

- guppylang/std/builtins.py
At some point during merging the rename from `Bool` to `bool` from commit https://github.com/CQCL/guppylang/pull/884 must have been accidentally reverted, causing issues with docs
> fix: Merge `Bool` and `bool` in builtins

- README.md
- quickstart.md
Also these two files contain some duplicatated content. Maybe would be worth having `teleport` in a single place.
> docs: replace `compile_module` usage in README

- guppylang/decorator.py
- tests/integration/test_custom_decorator.py
Fixes #1085
The previous approach of trying to get a reference to the calling function failed if the function was defined in a nested scope instead of globally. Now, we avoid the need to lookup a reference to the calling function by flagging custom decorators directly inside the code object
> fix: Correctly detect `@custom_guppy_decorator` in nested scopes

- guppylang/checker/expr_checker.py
- tests/error/comptime_arg_errors/unknown_cf_expr.err
- tests/error/comptime_arg_errors/unknown_cf_expr.py
> fix: Stop showing temporary variables in comptime diagnostics

- guppylang/engine.py
- tests/integration/test_poly_py312.py
> fix: Fix frame lookup for Python 3.12 annotation scopes

- guppylang/definition/function.py
- guppylang/definition/struct.py
- guppylang/ipython_inspect.py
- guppylang/span.py
- guppylang/tracing/object.py
- tests/integration/notebooks/comptime.ipynb
- tests/integration/notebooks/demo.ipynb
- tests/integration/notebooks/misc_notebook_tests.ipynb
Fixes #1053 and fixes #937
I finally found a way to fix our notebook problems in a way that's hopefully more stable than previous hacks. It relies on the internal [`format_code_name`](https://ipython.readthedocs.io/en/9.1.0/api/generated/IPython.core.compilerop.html#IPython.core.compilerop.CachingCompiler.format_code_name) IPython method that allows us to translate dummy file names generated by IPython into their corresponding cells. This allows us to get rid of previous attempts to find definitions by walking the AST of cells.
> fix: Fix Jupyter notebook diagnostic rendering

- guppylang/defs.py
- guppylang/emulator/__init__.py
- guppylang/emulator/builder.py
- guppylang/emulator/instance.py
- guppylang/emulator/result.py
- guppylang/emulator/state.py
First pass, should be improved in patch follow ups
> docs: add docstrings for emulator module

- guppylang-internals/src/guppylang_internals/decorator.py
> fix(guppylang-internals): Fix circular import for custom decorators

- release-please-config.json
The last `-internals` didn't update the `uv.lock` due to this typo.
> ci: Make sure release-please updates `-internals` version in uv.lock

- CHANGELOG.md
Updating this changelog with hand written elements so that there is a single source of truth for the langauge changelog. We can then use this markdown page in the docs website.
> docs: expand Guppylang changelog

- guppylang/CHANGELOG.md
redo of #1198. We have to go up another directory after the changelog moved one directory down #1181 
I probably won't put any more relative links here. Too annoying.
> docs: fix changelog after directory move

- guppylang/pyproject.toml
I think the README in the repository root with the logo, links etc is a better thing to put on the pypi page than the one inside the `guppylang` subdirectory.
Relevant comment from @aborgna-q 
https://github.com/CQCL/guppylang/pull/1181#discussion_r2269374023
Relative link should work I think? 
https://packaging.python.org/en/latest/specifications/pyproject-toml/#readme
> docs: use root README for pypi page

- guppylang/pyproject.toml
- tests/integration/test_emulator.py
- tests/integration/test_pytket_circuits.py
- tests/integration/test_wasm.py
- uv.lock
Adds a couple tests:
- Running the emulator on a program with `qsystem` primitives, and complex angle expressions.
- Running the emulator on a program translated from `pytket`, with the same qsystem primitives and expressions.
The second case fails with `tket 0.12.2` :)
~Kept as draft until we update tket with the fix.~
> test: Add pytket->selene execution test

- guppylang-internals/src/guppylang_internals/tracing/function.py
- guppylang-internals/src/guppylang_internals/tracing/unpacking.py
- tests/error/tracing_errors/cannot_borrow1.err
- tests/error/tracing_errors/cannot_borrow1.py
- tests/error/tracing_errors/cannot_borrow2.err
- tests/error/tracing_errors/cannot_borrow2.py
- tests/integration/tracing/test_basic.py
Fixes #1251
BREAKING CHANGE: `guppylang_internals.tracing.unpacking.update_packed_value` now returns a `bool` signalling whether the operation was successful.
Potential follow-up: Add a std library function to make a copy of Python values as Guppy objects that can then be borrowed and point to that function in the error message
> fix!: Correctly update borrowed values after calls and catch cases where it's impossible

- guppylang/src/guppylang/decorator.py
I think this will fix the bug that's [shown by ci on main](https://github.com/CQCL/guppylang/actions/runs/17736948523/job/50401037681)
> fix: Use qualified `extend_type` function

- README.md
in #1227 I made an update to use the root README for the guppylang package description. After the 0.21.4 release I see this has worked and the text is updated.
As you can see, the fish logo isn't showing properly. 
According to https://stackoverflow.com/questions/41983209/how-do-i-add-images-to-a-pypi-readme-that-works-on-github the fix is to link to the raw github user content rather than just the path to the directory. Hopefully this works.
> fix: update logo display to work on pypi page.

- .github/dependabot.yml
https://github.blog/changelog/2025-03-13-dependabot-version-updates-now-support-uv-in-general-availability/
> ci: Use `uv` ecosystem for dependabot python updates

- tests/integration/conftest.py
There's an issue with the exporting of hugrs generated while running integration tests. We just need to change the `validate` fixture to have `scope="function"`  (the default one), otherwise the hugr files are overwritten as the `request.node_name` is always None.
> chore: fix exporting integration tests
